project:
  type: website
  output-dir: docs

website:
  title: "Tarefa GC e Visualizadores - Juliana Louro"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    toc: true
css: styles.css


